### ISSUE TITLE
Lint js files

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2232]
Do we already have a standard how to lint our js file(s)? E.g.  [/src/zabapgit_js_common](https://github.com/larshp/abapGit/blob/master/src/zabapgit_js_common.w3mi.data.js)?

Jshint e.g. shows a bunch of warnings.
![image](https://user-images.githubusercontent.com/17437789/50480015-d8b7fb00-09d9-11e9-9189-d733a1bfb33d.png)

**Comment by sbcgua** [comment]
Good idea to lint js. Today's recommendation is to use eslint (not jshint). Though I cannot ground myself - I just used eslint. I'd just stock to one of ruleset e.g. "eslint:recommended" + some specifc rules. Here is my example I use. If no objections I can add a package.json command

```yaml
extends:
  - eslint:recommended
rules:
  quotes: ['error', 'single', { 'avoidEscape': true }]
  semi:   ['error', 'always', { 'omitLastInOneLineBlock': true}]
  no-console: off
  indent: ['error', 4]
  no-trailing-spaces: ['error']
```

**Comment by larshp** [comment]
eslint sounds good

**Comment by sbcgua** [comment]
Yeah ........ how many warnings did jshint show ? :)
![image](https://user-images.githubusercontent.com/15635498/50494372-88698900-0a2b-11e9-8fc2-885747cbba74.png)

proposed config

```yaml
parserOptions:
  ecmaVersion: 5
env:
  browser: true
extends:
  - eslint:recommended
rules:
  quotes: ['warn', 'single', { 'avoidEscape': true }]
  semi:   ['error', 'always', { 'omitLastInOneLineBlock': true}]
  no-console: off
  indent: ['error', 2]
  no-trailing-spaces: ['error']
```

doubts/questions:
- quotes ... since abapmerge escapes singlequotes - both are OK. I like single quotes ... but wrote most of the code with double (because initially there was no escaping)
- any other preferences to add ?
