### ISSUE TITLE
ABAP in eclipse: Menu overlay erroneous

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit#516]
When triggering the report within eclipse, the menu is hidden behind the files list

![2016-12-31 13_28_42](https://cloud.githubusercontent.com/assets/17176678/21577499/4520d550-cf5d-11e6-831c-c9cd5a3142a6.png)

IE11 is system browser.

**Comment by larshp** [comment]
hmm, and it works when running in SAP GUI? Any way you can run "Advanced -> Debug" info, it shows information about the browser version

**Comment by mrsimpson** [comment]
Fine in SAPGUI. 
Let me check the debug info. Anyway: not this year ;-)

**Comment by larshp** [comment]
Issue reproduced,

![image](https://cloud.githubusercontent.com/assets/5888506/21591747/1e377bc8-d107-11e6-99f9-fccb1c100f49.png)

![image](https://cloud.githubusercontent.com/assets/5888506/21591755/2fc7cb86-d107-11e6-955e-d0810faaa76c.png)

**Comment by larshp** [comment]
it looks like
```css
div.repo_container {
  position: relative;
}
```
relative is needed for the angled dropdown

does not work very well with
```css
.dropdown_content {
  display: none;
  z-index: 1;
  position: absolute;
  right: -12px;
  top: 1em;
  padding: 6px 10px 10px 10px;
  white-space: nowrap;
}
```

I suggest removing the fancy CSS angled menu containing options "Show files" + "Changed only" + "With folders" to a new "View" option on the same level as "Advanced" and "Refesh" menu options, @sbcgua any thoughts?
